// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/category/proto/category.proto

package category

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListCategoriesRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCategoriesRequest) Reset()         { *m = ListCategoriesRequest{} }
func (m *ListCategoriesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCategoriesRequest) ProtoMessage()    {}
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_63066037b18693f0, []int{0}
}
func (m *ListCategoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoriesRequest.Unmarshal(m, b)
}
func (m *ListCategoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoriesRequest.Marshal(b, m, deterministic)
}
func (dst *ListCategoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoriesRequest.Merge(dst, src)
}
func (m *ListCategoriesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCategoriesRequest.Size(m)
}
func (m *ListCategoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoriesRequest proto.InternalMessageInfo

func (m *ListCategoriesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCategoriesRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type ListCategoriesResponse struct {
	Categories           []*SingleCategory `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	PageSize             int32             `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32             `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListCategoriesResponse) Reset()         { *m = ListCategoriesResponse{} }
func (m *ListCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*ListCategoriesResponse) ProtoMessage()    {}
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_63066037b18693f0, []int{1}
}
func (m *ListCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoriesResponse.Unmarshal(m, b)
}
func (m *ListCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoriesResponse.Marshal(b, m, deterministic)
}
func (dst *ListCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoriesResponse.Merge(dst, src)
}
func (m *ListCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_ListCategoriesResponse.Size(m)
}
func (m *ListCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoriesResponse proto.InternalMessageInfo

func (m *ListCategoriesResponse) GetCategories() []*SingleCategory {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *ListCategoriesResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListCategoriesResponse) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type SingleCategory struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	UserUid              string   `protobuf:"bytes,2,opt,name=userUid,proto3" json:"userUid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleCategory) Reset()         { *m = SingleCategory{} }
func (m *SingleCategory) String() string { return proto.CompactTextString(m) }
func (*SingleCategory) ProtoMessage()    {}
func (*SingleCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_63066037b18693f0, []int{2}
}
func (m *SingleCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleCategory.Unmarshal(m, b)
}
func (m *SingleCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleCategory.Marshal(b, m, deterministic)
}
func (dst *SingleCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleCategory.Merge(dst, src)
}
func (m *SingleCategory) XXX_Size() int {
	return xxx_messageInfo_SingleCategory.Size(m)
}
func (m *SingleCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleCategory.DiscardUnknown(m)
}

var xxx_messageInfo_SingleCategory proto.InternalMessageInfo

func (m *SingleCategory) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SingleCategory) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

func (m *SingleCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SingleCategory) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateCategoryRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	UserUid              string   `protobuf:"bytes,3,opt,name=userUid,proto3" json:"userUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCategoryRequest) Reset()         { *m = CreateCategoryRequest{} }
func (m *CreateCategoryRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCategoryRequest) ProtoMessage()    {}
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_63066037b18693f0, []int{3}
}
func (m *CreateCategoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCategoryRequest.Unmarshal(m, b)
}
func (m *CreateCategoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCategoryRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCategoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCategoryRequest.Merge(dst, src)
}
func (m *CreateCategoryRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCategoryRequest.Size(m)
}
func (m *CreateCategoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCategoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCategoryRequest proto.InternalMessageInfo

func (m *CreateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCategoryRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateCategoryRequest) GetUserUid() string {
	if m != nil {
		return m.UserUid
	}
	return ""
}

type GetCategoryInfoRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCategoryInfoRequest) Reset()         { *m = GetCategoryInfoRequest{} }
func (m *GetCategoryInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetCategoryInfoRequest) ProtoMessage()    {}
func (*GetCategoryInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_63066037b18693f0, []int{4}
}
func (m *GetCategoryInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCategoryInfoRequest.Unmarshal(m, b)
}
func (m *GetCategoryInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCategoryInfoRequest.Marshal(b, m, deterministic)
}
func (dst *GetCategoryInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCategoryInfoRequest.Merge(dst, src)
}
func (m *GetCategoryInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetCategoryInfoRequest.Size(m)
}
func (m *GetCategoryInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCategoryInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCategoryInfoRequest proto.InternalMessageInfo

func (m *GetCategoryInfoRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type ListReportsRequest struct {
	CategoryUid          string   `protobuf:"bytes,1,opt,name=categoryUid,proto3" json:"categoryUid,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32    `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReportsRequest) Reset()         { *m = ListReportsRequest{} }
func (m *ListReportsRequest) String() string { return proto.CompactTextString(m) }
func (*ListReportsRequest) ProtoMessage()    {}
func (*ListReportsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_63066037b18693f0, []int{5}
}
func (m *ListReportsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReportsRequest.Unmarshal(m, b)
}
func (m *ListReportsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReportsRequest.Marshal(b, m, deterministic)
}
func (dst *ListReportsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReportsRequest.Merge(dst, src)
}
func (m *ListReportsRequest) XXX_Size() int {
	return xxx_messageInfo_ListReportsRequest.Size(m)
}
func (m *ListReportsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReportsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListReportsRequest proto.InternalMessageInfo

func (m *ListReportsRequest) GetCategoryUid() string {
	if m != nil {
		return m.CategoryUid
	}
	return ""
}

func (m *ListReportsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListReportsRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type ListReportsResponse struct {
	Reports              []*SingleReport `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	PageSize             int32           `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber           int32           `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListReportsResponse) Reset()         { *m = ListReportsResponse{} }
func (m *ListReportsResponse) String() string { return proto.CompactTextString(m) }
func (*ListReportsResponse) ProtoMessage()    {}
func (*ListReportsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_63066037b18693f0, []int{6}
}
func (m *ListReportsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReportsResponse.Unmarshal(m, b)
}
func (m *ListReportsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReportsResponse.Marshal(b, m, deterministic)
}
func (dst *ListReportsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReportsResponse.Merge(dst, src)
}
func (m *ListReportsResponse) XXX_Size() int {
	return xxx_messageInfo_ListReportsResponse.Size(m)
}
func (m *ListReportsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReportsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListReportsResponse proto.InternalMessageInfo

func (m *ListReportsResponse) GetReports() []*SingleReport {
	if m != nil {
		return m.Reports
	}
	return nil
}

func (m *ListReportsResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListReportsResponse) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

type CreateReportRequest struct {
	CategoryUid          string   `protobuf:"bytes,1,opt,name=categoryUid,proto3" json:"categoryUid,omitempty"`
	PostUid              string   `protobuf:"bytes,2,opt,name=postUid,proto3" json:"postUid,omitempty"`
	CommentUid           string   `protobuf:"bytes,3,opt,name=commentUid,proto3" json:"commentUid,omitempty"`
	Reason               string   `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReportRequest) Reset()         { *m = CreateReportRequest{} }
func (m *CreateReportRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReportRequest) ProtoMessage()    {}
func (*CreateReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_63066037b18693f0, []int{7}
}
func (m *CreateReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReportRequest.Unmarshal(m, b)
}
func (m *CreateReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReportRequest.Marshal(b, m, deterministic)
}
func (dst *CreateReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReportRequest.Merge(dst, src)
}
func (m *CreateReportRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReportRequest.Size(m)
}
func (m *CreateReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReportRequest proto.InternalMessageInfo

func (m *CreateReportRequest) GetCategoryUid() string {
	if m != nil {
		return m.CategoryUid
	}
	return ""
}

func (m *CreateReportRequest) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

func (m *CreateReportRequest) GetCommentUid() string {
	if m != nil {
		return m.CommentUid
	}
	return ""
}

func (m *CreateReportRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type SingleReport struct {
	Uid                  string               `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	CategoryUid          string               `protobuf:"bytes,2,opt,name=categoryUid,proto3" json:"categoryUid,omitempty"`
	PostUid              string               `protobuf:"bytes,3,opt,name=postUid,proto3" json:"postUid,omitempty"`
	CommentUid           string               `protobuf:"bytes,4,opt,name=commentUid,proto3" json:"commentUid,omitempty"`
	Reason               string               `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SingleReport) Reset()         { *m = SingleReport{} }
func (m *SingleReport) String() string { return proto.CompactTextString(m) }
func (*SingleReport) ProtoMessage()    {}
func (*SingleReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_63066037b18693f0, []int{8}
}
func (m *SingleReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleReport.Unmarshal(m, b)
}
func (m *SingleReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleReport.Marshal(b, m, deterministic)
}
func (dst *SingleReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleReport.Merge(dst, src)
}
func (m *SingleReport) XXX_Size() int {
	return xxx_messageInfo_SingleReport.Size(m)
}
func (m *SingleReport) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleReport.DiscardUnknown(m)
}

var xxx_messageInfo_SingleReport proto.InternalMessageInfo

func (m *SingleReport) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *SingleReport) GetCategoryUid() string {
	if m != nil {
		return m.CategoryUid
	}
	return ""
}

func (m *SingleReport) GetPostUid() string {
	if m != nil {
		return m.PostUid
	}
	return ""
}

func (m *SingleReport) GetCommentUid() string {
	if m != nil {
		return m.CommentUid
	}
	return ""
}

func (m *SingleReport) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *SingleReport) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

type DeleteReportRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReportRequest) Reset()         { *m = DeleteReportRequest{} }
func (m *DeleteReportRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteReportRequest) ProtoMessage()    {}
func (*DeleteReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_63066037b18693f0, []int{9}
}
func (m *DeleteReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReportRequest.Unmarshal(m, b)
}
func (m *DeleteReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReportRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReportRequest.Merge(dst, src)
}
func (m *DeleteReportRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteReportRequest.Size(m)
}
func (m *DeleteReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReportRequest proto.InternalMessageInfo

func (m *DeleteReportRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type DeleteReportResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReportResponse) Reset()         { *m = DeleteReportResponse{} }
func (m *DeleteReportResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteReportResponse) ProtoMessage()    {}
func (*DeleteReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_63066037b18693f0, []int{10}
}
func (m *DeleteReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReportResponse.Unmarshal(m, b)
}
func (m *DeleteReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReportResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReportResponse.Merge(dst, src)
}
func (m *DeleteReportResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteReportResponse.Size(m)
}
func (m *DeleteReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReportResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListCategoriesRequest)(nil), "category.ListCategoriesRequest")
	proto.RegisterType((*ListCategoriesResponse)(nil), "category.ListCategoriesResponse")
	proto.RegisterType((*SingleCategory)(nil), "category.SingleCategory")
	proto.RegisterType((*CreateCategoryRequest)(nil), "category.CreateCategoryRequest")
	proto.RegisterType((*GetCategoryInfoRequest)(nil), "category.GetCategoryInfoRequest")
	proto.RegisterType((*ListReportsRequest)(nil), "category.ListReportsRequest")
	proto.RegisterType((*ListReportsResponse)(nil), "category.ListReportsResponse")
	proto.RegisterType((*CreateReportRequest)(nil), "category.CreateReportRequest")
	proto.RegisterType((*SingleReport)(nil), "category.SingleReport")
	proto.RegisterType((*DeleteReportRequest)(nil), "category.DeleteReportRequest")
	proto.RegisterType((*DeleteReportResponse)(nil), "category.DeleteReportResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CategoryClient is the client API for Category service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CategoryClient interface {
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	GetCategoryInfo(ctx context.Context, in *GetCategoryInfoRequest, opts ...grpc.CallOption) (*SingleCategory, error)
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*SingleCategory, error)
	ListReports(ctx context.Context, in *ListReportsRequest, opts ...grpc.CallOption) (*ListReportsResponse, error)
	CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*SingleReport, error)
	DeleteReport(ctx context.Context, in *DeleteReportRequest, opts ...grpc.CallOption) (*DeleteReportResponse, error)
}

type categoryClient struct {
	cc *grpc.ClientConn
}

func NewCategoryClient(cc *grpc.ClientConn) CategoryClient {
	return &categoryClient{cc}
}

func (c *categoryClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, "/category.Category/ListCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryClient) GetCategoryInfo(ctx context.Context, in *GetCategoryInfoRequest, opts ...grpc.CallOption) (*SingleCategory, error) {
	out := new(SingleCategory)
	err := c.cc.Invoke(ctx, "/category.Category/GetCategoryInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*SingleCategory, error) {
	out := new(SingleCategory)
	err := c.cc.Invoke(ctx, "/category.Category/CreateCategory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryClient) ListReports(ctx context.Context, in *ListReportsRequest, opts ...grpc.CallOption) (*ListReportsResponse, error) {
	out := new(ListReportsResponse)
	err := c.cc.Invoke(ctx, "/category.Category/ListReports", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryClient) CreateReport(ctx context.Context, in *CreateReportRequest, opts ...grpc.CallOption) (*SingleReport, error) {
	out := new(SingleReport)
	err := c.cc.Invoke(ctx, "/category.Category/CreateReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryClient) DeleteReport(ctx context.Context, in *DeleteReportRequest, opts ...grpc.CallOption) (*DeleteReportResponse, error) {
	out := new(DeleteReportResponse)
	err := c.cc.Invoke(ctx, "/category.Category/DeleteReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryServer is the server API for Category service.
type CategoryServer interface {
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	GetCategoryInfo(context.Context, *GetCategoryInfoRequest) (*SingleCategory, error)
	CreateCategory(context.Context, *CreateCategoryRequest) (*SingleCategory, error)
	ListReports(context.Context, *ListReportsRequest) (*ListReportsResponse, error)
	CreateReport(context.Context, *CreateReportRequest) (*SingleReport, error)
	DeleteReport(context.Context, *DeleteReportRequest) (*DeleteReportResponse, error)
}

func RegisterCategoryServer(s *grpc.Server, srv CategoryServer) {
	s.RegisterService(&_Category_serviceDesc, srv)
}

func _Category_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/category.Category/ListCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Category_GetCategoryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).GetCategoryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/category.Category/GetCategoryInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).GetCategoryInfo(ctx, req.(*GetCategoryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Category_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/category.Category/CreateCategory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Category_ListReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).ListReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/category.Category/ListReports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).ListReports(ctx, req.(*ListReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Category_CreateReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).CreateReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/category.Category/CreateReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).CreateReport(ctx, req.(*CreateReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Category_DeleteReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).DeleteReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/category.Category/DeleteReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).DeleteReport(ctx, req.(*DeleteReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Category_serviceDesc = grpc.ServiceDesc{
	ServiceName: "category.Category",
	HandlerType: (*CategoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCategories",
			Handler:    _Category_ListCategories_Handler,
		},
		{
			MethodName: "GetCategoryInfo",
			Handler:    _Category_GetCategoryInfo_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _Category_CreateCategory_Handler,
		},
		{
			MethodName: "ListReports",
			Handler:    _Category_ListReports_Handler,
		},
		{
			MethodName: "CreateReport",
			Handler:    _Category_CreateReport_Handler,
		},
		{
			MethodName: "DeleteReport",
			Handler:    _Category_DeleteReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/category/proto/category.proto",
}

func init() {
	proto.RegisterFile("pkg/category/proto/category.proto", fileDescriptor_category_63066037b18693f0)
}

var fileDescriptor_category_63066037b18693f0 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xe3, 0x34, 0x3f, 0x93, 0x28, 0xa0, 0x0d, 0x8d, 0x2c, 0x8b, 0xb6, 0xc6, 0x17, 0x22,
	0x0e, 0x09, 0x0a, 0x97, 0x5e, 0x51, 0x41, 0x88, 0x9f, 0x72, 0x70, 0xe8, 0x03, 0x38, 0xce, 0xd4,
	0xb2, 0x88, 0xbd, 0x66, 0x77, 0x7d, 0x08, 0x57, 0x4e, 0x5c, 0x78, 0x34, 0xde, 0x80, 0x77, 0x41,
	0xf1, 0x5f, 0x76, 0x1d, 0xdb, 0xaa, 0xd4, 0xdb, 0xce, 0xec, 0xec, 0xb7, 0xdf, 0xcc, 0x7c, 0x33,
	0xf0, 0x22, 0xfe, 0xee, 0x2f, 0x3d, 0x57, 0xa0, 0x4f, 0xd9, 0x7e, 0x19, 0x33, 0x2a, 0x68, 0x69,
	0x2e, 0x52, 0x93, 0x0c, 0x0a, 0xdb, 0xbc, 0xf2, 0x29, 0xf5, 0x77, 0x98, 0x85, 0x6d, 0x92, 0xfb,
	0xa5, 0x08, 0x42, 0xe4, 0xc2, 0x0d, 0xe3, 0x2c, 0xd4, 0x5e, 0xc3, 0xf9, 0x97, 0x80, 0x8b, 0x9b,
	0xec, 0x41, 0x80, 0xdc, 0xc1, 0x1f, 0x09, 0x72, 0x41, 0x4c, 0x18, 0xc4, 0xae, 0x8f, 0xeb, 0xe0,
	0x27, 0x1a, 0x9a, 0xa5, 0xcd, 0xcf, 0x9c, 0xd2, 0x26, 0x97, 0x00, 0x87, 0xf3, 0xd7, 0x24, 0xdc,
	0x20, 0x33, 0x3a, 0xe9, 0xad, 0xe4, 0xb1, 0xff, 0x68, 0x30, 0xab, 0xa2, 0xf2, 0x98, 0x46, 0x1c,
	0xc9, 0x35, 0x80, 0x57, 0x7a, 0x0d, 0xcd, 0xd2, 0xe7, 0xa3, 0x95, 0xb1, 0x28, 0xf9, 0xaf, 0x83,
	0xc8, 0xdf, 0x61, 0xfe, 0x6e, 0xef, 0x48, 0xb1, 0x0a, 0xa1, 0x4e, 0x2b, 0x21, 0xfd, 0x84, 0x10,
	0x83, 0x89, 0x8a, 0x4c, 0x9e, 0x82, 0x9e, 0x04, 0xdb, 0x34, 0xb3, 0xa1, 0x73, 0x38, 0x12, 0x03,
	0xfa, 0x09, 0x47, 0x76, 0x17, 0x6c, 0x53, 0xf8, 0xa1, 0x53, 0x98, 0x84, 0x40, 0x37, 0x72, 0x43,
	0x4c, 0x71, 0x87, 0x4e, 0x7a, 0x26, 0x16, 0x8c, 0xb6, 0xc8, 0x3d, 0x16, 0xc4, 0x22, 0xa0, 0x91,
	0xd1, 0x4d, 0xaf, 0x64, 0x97, 0xed, 0xc3, 0xf9, 0x0d, 0x43, 0x57, 0x1c, 0xb3, 0xc9, 0x2b, 0x5b,
	0xc0, 0x69, 0xcd, 0x70, 0x9d, 0x13, 0x38, 0x99, 0x9e, 0xae, 0xd0, 0xb3, 0x5f, 0xc1, 0xec, 0x03,
	0x16, 0xb5, 0xde, 0x7f, 0x8c, 0xee, 0x69, 0xf1, 0xd3, 0x49, 0x92, 0x36, 0x03, 0x72, 0x68, 0x8c,
	0x83, 0x31, 0x65, 0xa2, 0xec, 0xb5, 0x05, 0xa3, 0xa2, 0x03, 0x77, 0x65, 0xbc, 0xec, 0x7a, 0x54,
	0xf1, 0x7f, 0x69, 0x30, 0x55, 0x3e, 0xcd, 0xa5, 0xf0, 0x1a, 0xfa, 0x2c, 0x73, 0xe5, 0x3a, 0x98,
	0x55, 0x75, 0x90, 0xbd, 0x70, 0x8a, 0xb0, 0x47, 0xb1, 0xf8, 0xad, 0xc1, 0x34, 0xeb, 0x47, 0x8e,
	0xfa, 0xe0, 0xdc, 0x0d, 0xe8, 0xc7, 0x94, 0x0b, 0x49, 0x18, 0xb9, 0x79, 0xf8, 0xd3, 0xa3, 0x61,
	0x88, 0x91, 0x38, 0xb6, 0x45, 0xf2, 0x90, 0x19, 0xf4, 0x18, 0xba, 0xbc, 0xd4, 0x47, 0x6e, 0xd9,
	0x7f, 0x35, 0x18, 0xcb, 0x19, 0xd6, 0xa8, 0xb1, 0x42, 0xab, 0xd3, 0x4a, 0x4b, 0x6f, 0xa3, 0xd5,
	0x6d, 0xa1, 0x75, 0x26, 0xd3, 0x22, 0xd7, 0x30, 0xf4, 0xd2, 0x0a, 0x6d, 0xdf, 0x0a, 0xa3, 0x67,
	0x69, 0xf3, 0xd1, 0xca, 0x5c, 0x64, 0x0b, 0x64, 0x51, 0x2c, 0x90, 0xc5, 0xb7, 0x62, 0x81, 0x38,
	0xc7, 0x60, 0xfb, 0x25, 0x4c, 0xdf, 0xe1, 0x0e, 0xab, 0xb5, 0x3d, 0xd5, 0xdf, 0x0c, 0x9e, 0xa9,
	0x81, 0x99, 0x16, 0x56, 0xff, 0x74, 0x18, 0x94, 0xb3, 0xb9, 0x86, 0x89, 0xba, 0x3d, 0xc8, 0xd5,
	0x51, 0x19, 0xb5, 0xdb, 0xca, 0xb4, 0x9a, 0x03, 0x72, 0xb5, 0xdd, 0xc2, 0x93, 0xca, 0x94, 0x10,
	0xe9, 0x51, 0xfd, 0x00, 0x99, 0x8d, 0x9b, 0x89, 0x7c, 0x86, 0x89, 0x3a, 0xdd, 0x32, 0xc7, 0xda,
	0xb9, 0x6f, 0x01, 0xfb, 0x04, 0x23, 0x69, 0x40, 0xc8, 0x73, 0x35, 0x19, 0x75, 0x58, 0xcd, 0x8b,
	0x86, 0xdb, 0x3c, 0xcf, 0xf7, 0x30, 0x96, 0x65, 0x4e, 0x2e, 0xaa, 0xb4, 0x94, 0x16, 0x99, 0x0d,
	0x33, 0x47, 0x6e, 0x61, 0x2c, 0x37, 0x4a, 0x86, 0xa9, 0xe9, 0xb4, 0x79, 0xd9, 0x74, 0x9d, 0xb1,
	0xda, 0xf4, 0x52, 0xfd, 0xbc, 0xf9, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x5e, 0xd7, 0x01, 0xbd,
	0x06, 0x00, 0x00,
}
